# Microsoft already had an image for presidio.
# Official Presidio Analyzer container
FROM mcr.microsoft.com/presidio-analyzer:latest

# Expose the API port
EXPOSE 3000

#Reminder to use:
# docker run -p 3000:3000 mcr.microsoft.com/presidio-analyzer:latest
